version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/test-github-action-rails
      - /test-github-action-rails/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: dbpass
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
